"""
Django settings for myproject project.
Generated by 'django-admin startproject' using Django 5.2.x.
For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/
"""

from pathlib import Path
import os
import dj_database_url

BASE_DIR = Path(__file__).resolve().parent.parent

# --- CORE SECURITY / DEPLOYMENT SETTINGS ---

# Secret Key (ดึงจาก Env Variable เพื่อความปลอดภัย)
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "unsafe-secret-key")
# ลบ ALT_SECRET_KEY ออก เนื่องจากไม่จำเป็นและเป็น Hardcoded

# Debug Mode (ดึงจาก Env Variable)
DEBUG = os.getenv("DJANGO_DEBUG", "False").lower() in ("true", "1")

# Allowed Hosts (ใช้ os.getenv เพื่อความยืดหยุ่นในการ Deploy บน Render)
ALLOWED_HOSTS = os.getenv(
    "DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1,cn331-as2-jmb3.onrender.com"
).split(",")

# Database (ใช้ dj_database_url เพื่อรองรับ Postgres บน Render)
DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}

# --- APPLICATION DEFINITION ---

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "booking", # แอปของคุณ
]

# --- AUTH REDIRECTS ---
# ใช้ URL Name ("login", "rooms") แทน Path เพื่อความยืดหยุ่น
LOGIN_URL = "login"
LOGOUT_REDIRECT_URL = "home" # ปรับเป็น 'home' เพื่อให้กลับหน้าหลักหลัง logout

# --- MIDDLEWARE ---
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "myproject.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "myproject.wsgi.application"

# --- PASSWORD VALIDATION ---
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# --- INTERNATIONALIZATION / STATIC FILES ---
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"