name: Run Django Unit Tests

on:
  push:
    branches:
      - testing

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: 'ci-testing-secret-key' 
      DJANGO_SETTINGS_MODULE: myproject.settings

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 

      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.10'

      - name: Install dependencies (with coverage)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # ตรวจสอบให้แน่ใจว่า coverage ถูกติดตั้ง แม้ว่าจะมีใน requirements.txt แล้วก็ตาม
          pip install coverage 

      - name: Run Tests and Generate Coverage Report
        run: |
          # 1. รัน Unit Tests พร้อมวัด Coverage
          coverage run manage.py test
          
          # 2. แสดงตาราง Coverage Report ใน Log (นี่คือหลักฐานที่คุณต้องการ)
          echo "--- FINAL CODE COVERAGE REPORT ---"
          coverage report
          
          # 3. หากต้องการไฟล์ HTML report (สำหรับดาวน์โหลด)
          # coverage html -d coverage_html_report